### ISSUE TITLE
No such image: error

### ISSUE THREAD

**Issue by jordiclive** [danieldeutsch/repro#130]
Trying to run the demo. When I run

```
lewis2020 = BART(model="bart.large.cnn")
summary2 = lewis2020.predict(document)
```
I Get 
`Not Found ("no such image: danieldeutsch/lewis2020:1.1: No such image: danieldeutsch/lewis2020:1.1")`
and for dou
`404 Client Error for http+docker://localhost/v1.41/images/danieldeutsch/dou2021:1.0/json: Not Found ("no such image: danieldeutsch/dou2021:1.0: No such image: danieldeutsch/dou2021:1.0")`

But this model works
``liu2019 = BertSumExtAbs(device=0) ``

**Comment by danieldeutsch** [comment]
Very strange! Both images do exist on Docker Hub ([Lewis](https://hub.docker.com/repository/docker/danieldeutsch/lewis2020), [Dou](https://hub.docker.com/repository/docker/danieldeutsch/dou2021)). If the Docker image does not exist on your machine, it should be automatically downloaded.

Could you try running `docker pull danieldeutsch/lewis2020:1.1` and `docker pull danieldeutsch/dou2021:1.0`, then retrying the demo code? This should not be necessary, but it will help identify where the problem is.

**Comment by danieldeutsch** [comment]
It looks like the `dou2021` image may be stale. My DockerHub account uses the free tier, and it seems like they may delete images after they haven't been used for some time. If this is the case, I will investigate upgrading my membership.

The `lewis2020` image should not be affected by this, though. The 1.1 tag was pushed 2 months ago.

**Comment by jordiclive** [comment]
Ah ok. it's working after I ran docker pull :).

**Comment by danieldeutsch** [comment]
This error should not happen because the Docker python library automatically downloads the images if they don't exist, so perhaps the downloads failed for some reason? 🤷‍♂️ Anyway, glad it's fixed

**Comment by jordiclive** [comment]
Thanks :)  I just tried again on a fresh EC2 instance and worked without docker pull.
